/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/profile/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/profile/settings/admin/manageMemberships/AddMember`; params?: Router.UnknownInputParams; } | { pathname: `/profile/settings/admin/manageMemberships/AddMemberConfirm`; params?: Router.UnknownInputParams; } | { pathname: `/profile/settings/admin/manageMemberships/EditMember`; params?: Router.UnknownInputParams; } | { pathname: `/profile/settings/admin/manageMemberships/viewMembers`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/MyPass`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/learn`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/scan`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signUp`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/EditProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/settings/admin/manageMemberships/AddMember`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/settings/admin/manageMemberships/AddMemberConfirm`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/settings/admin/manageMemberships/EditMember`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/settings/admin/manageMemberships/viewMembers`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/MyPass`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/learn`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/scan`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/Login${`?${string}` | `#${string}` | ''}` | `/auth/signUp${`?${string}` | `#${string}` | ''}` | `/auth/welcome${`?${string}` | `#${string}` | ''}` | `/profile/EditProfile${`?${string}` | `#${string}` | ''}` | `/profile/Settings${`?${string}` | `#${string}` | ''}` | `/profile/settings/admin/manageMemberships/AddMember${`?${string}` | `#${string}` | ''}` | `/profile/settings/admin/manageMemberships/AddMemberConfirm${`?${string}` | `#${string}` | ''}` | `/profile/settings/admin/manageMemberships/EditMember${`?${string}` | `#${string}` | ''}` | `/profile/settings/admin/manageMemberships/viewMembers${`?${string}` | `#${string}` | ''}` | `/tabs/MyPass${`?${string}` | `#${string}` | ''}` | `/tabs/Profile${`?${string}` | `#${string}` | ''}` | `/tabs/learn${`?${string}` | `#${string}` | ''}` | `/tabs/scan${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/profile/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/profile/settings/admin/manageMemberships/AddMember`; params?: Router.UnknownInputParams; } | { pathname: `/profile/settings/admin/manageMemberships/AddMemberConfirm`; params?: Router.UnknownInputParams; } | { pathname: `/profile/settings/admin/manageMemberships/EditMember`; params?: Router.UnknownInputParams; } | { pathname: `/profile/settings/admin/manageMemberships/viewMembers`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/MyPass`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/learn`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/scan`; params?: Router.UnknownInputParams; };
    }
  }
}
